site_name: Entornos de desarrollo
site_url: https://garmarcj.github.io/DAM-ED-20262027/
site_author: Cristian Garcia
theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: purple
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
nav:
  - Inicio: index.md
  - Unidad 1: unidad1.md
  - Unidad 2: unidad2.md
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
plugins:
  - with-pdf:
      output_path: pdf/entornosdedesarrollo.pdf
      cover: true
      toc_title: "entornos de desarrollo"
      exclude_pages:
        - licencia.md